/**
 * Created by caoyi on 2016/12/20.
 */
cStoreDist = {
    "data": [
    {
        "countyCode": "11011400",
        "countyName": "东城区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "7",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011400",
                "countyName": "东城区",
                "name": "北京国美富贵园店",
                "address": "北京市东城区富贵园三区家乐福底商",
                "storeHQCode": "A012",
                "storePhone": "67115175",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011100",
        "countyName": "大兴区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "4",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "国美电器有限公司北京大兴第二商城",
                "address": "北京市大兴区黄村镇兴华大街西侧",
                "storeHQCode": "A00L",
                "storePhone": "69242874",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "18",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京国美西红门店",
                "address": "北京市大兴区西红门镇七村村委会南300米一层",
                "storeHQCode": "A01M",
                "storePhone": "60240742",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "27",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京国美亦庄店",
                "address": "北京大兴区亦庄镇西环北路18号",
                "storeHQCode": "A00T",
                "storePhone": "67826079",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "28",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京国美大兴一店",
                "address": "北京市大兴区黄村镇兴丰南大街星城商厦五层国美电器",
                "storeHQCode": "A00M",
                "storePhone": "69242023",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10129",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京大中大兴店",
                "address": "北京市大兴区黄村东大街37号",
                "storeHQCode": "A0HB",
                "storePhone": "69241639",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10133",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京大中旧宫店",
                "address": "北京市大兴区旧宫镇旧宫西路21号",
                "storeHQCode": "A0H8",
                "storePhone": "56085200",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10135",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京大中亦庄店",
                "address": "北京市大兴区亦庄天宝北街一号",
                "storeHQCode": "A0HM",
                "storePhone": "56085152",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10136",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011100",
                "countyName": "大兴区",
                "name": "北京大中大兴家居广场店",
                "address": "北京市大兴区西红门镇七村双星桥西200米（日月星辰旁）",
                "storeHQCode": "A0IC",
                "storePhone": "60290699",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010800",
        "countyName": "通州区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "17",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010800",
                "countyName": "通州区",
                "name": "北京国美通州二店",
                "address": "北京市通州区九棵树家乐福四层国美电器",
                "storeHQCode": "A00U",
                "storePhone": "81512759",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10137",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010800",
                "countyName": "通州区",
                "name": "北京大中果园店",
                "address": "北京市通州区通朝大街208号",
                "storeHQCode": "A0HN",
                "storePhone": "58015244",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "42",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010800",
                "countyName": "通州区",
                "name": "北京大中通州店",
                "address": "北京市通州区新华大街256号",
                "storeHQCode": "A0H5",
                "storePhone": "80883075",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010600",
        "countyName": "门头沟区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "10151",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010600",
                "countyName": "门头沟区",
                "name": "北京大中门头沟店",
                "address": "北京市门头沟区河滩路1号",
                "storeHQCode": "A0GZ",
                "storePhone": "56085456",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010700",
        "countyName": "房山区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "15",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010700",
                "countyName": "房山区",
                "name": "北京国美良乡店",
                "address": "北京市房山区拱辰大街38号",
                "storeHQCode": "A00N",
                "storePhone": "69382820",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10139",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010700",
                "countyName": "房山区",
                "name": "北京大中房山店",
                "address": "北京市房山区城关镇南大街24号",
                "storeHQCode": "A0H2",
                "storePhone": "56085488",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10125",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010700",
                "countyName": "房山区",
                "name": "北京大中昊天广场店",
                "address": "北京市房山区良乡镇拱辰大街94号",
                "storeHQCode": "A0I7",
                "storePhone": "56084130",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010500",
        "countyName": "海淀区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "3",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京国美北太店",
                "address": "北京市海淀区北三环中路乙40号",
                "storeHQCode": "A002",
                "storePhone": "62072505",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "5",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京公主坟店",
                "address": "北京市海淀区复兴路21号海育大厦",
                "storeHQCode": "A013",
                "storePhone": "68513065",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "14",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京国美清河店",
                "address": "北京市海淀区清河永泰庄路25号泰鑫源商厦国美电器底商",
                "storeHQCode": "A00S",
                "storePhone": "82754973",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "19",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京世纪金源店",
                "address": "北京市海淀区远大路1号世纪金源购物中心",
                "storeHQCode": "A00B",
                "storePhone": "88876800",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "21",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京国美四季青桥旗舰店",
                "address": "北京市海淀区西四环北路119号爱家家居二层",
                "storeHQCode": "A017",
                "storePhone": "88436498",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "25",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京国美西三环店",
                "address": "北京市海淀区西三环北路105号科原大厦底商国美电器",
                "storeHQCode": "A005",
                "storePhone": "68710866",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "35",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京大中中塔店",
                "address": "北京市海淀区西三环中路11号",
                "storeHQCode": "A0GW",
                "storePhone": "56085511",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10147",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010500",
                "countyName": "海淀区",
                "name": "北京大中小营店",
                "address": "北京市海淀区清河小营通厦建材城",
                "storeHQCode": "A0GT",
                "storePhone": "56084499",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011700",
        "countyName": "密云区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "10141",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011700",
                "countyName": "密云区",
                "name": "北京大中密东广场店",
                "address": "北京市密云县鼓楼东大街23-6大中电器",
                "storeHQCode": "A0IF",
                "storePhone": "69027566",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10127",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011700",
                "countyName": "密云区",
                "name": "北京大中密云店",
                "address": "北京市密云县长安街1号大中电器",
                "storeHQCode": "A0HC",
                "storePhone": "69029827",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "32",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011700",
                "countyName": "密云区",
                "name": "北京国美密云店",
                "address": "北京市密云区密云镇鼓楼北大街10号",
                "storeHQCode": "A00E",
                "storePhone": "89080082",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010200",
        "countyName": "朝阳区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "1",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美安贞店",
                "address": "北京市朝阳区北三环中路浙江大厦裙房国美电器",
                "storeHQCode": "A00G",
                "storePhone": "64425170",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "6",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美管庄环岛店",
                "address": "北京市朝阳区朝阳路杨闸环岛中百世贸1层",
                "storeHQCode": "A01I",
                "storePhone": "51397729",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美西坝河店",
                "address": "北京市朝阳区北三环东路甲7号",
                "storeHQCode": "A007",
                "storePhone": "64270139",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "20",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美望京店",
                "address": "北京市朝阳区望京街9号望京商业中心B座",
                "storeHQCode": "A00O",
                "storePhone": "59203100",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "30",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美双井二店",
                "address": "北京市朝阳区广渠门外大街1号院底商",
                "storeHQCode": "A00W",
                "storePhone": "58623091",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "31",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京国美十里河店",
                "address": "北京市朝阳区大羊坊路106号",
                "storeHQCode": "A00F",
                "storePhone": "87365261",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "40",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中广渠路店",
                "address": "北京市朝阳区广渠路大街31号",
                "storeHQCode": "A0I6",
                "storePhone": "87769778",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10132",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中团结湖店",
                "address": "北京市团结湖朝阳北路219号",
                "storeHQCode": "A0HR",
                "storePhone": "56085088",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10138",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中立水桥店",
                "address": "北京市朝阳区安立路立水桥南甲1号",
                "storeHQCode": "A0HT",
                "storePhone": "56084414",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10140",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中望京国际店",
                "address": "北京市朝阳区望京街9号望京国际商业中心大中电器",
                "storeHQCode": "A0I3",
                "storePhone": "56085607",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10142",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中望京店",
                "address": "北京市朝阳区望京南湖中园130号大中电器",
                "storeHQCode": "A0HF",
                "storePhone": "56084622",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10146",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中大山子店",
                "address": "北京市朝阳区酒仙桥街道酒仙桥路2号大中电器",
                "storeHQCode": "A0GU",
                "storePhone": "56084555",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10150",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010200",
                "countyName": "朝阳区",
                "name": "北京大中双井店",
                "address": "北京市朝阳区广渠门外大街甲8号",
                "storeHQCode": "A0HL",
                "storePhone": "56084310",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011500",
        "countyName": "西城区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "34",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011500",
                "countyName": "西城区",
                "name": "北京大中马甸桥店",
                "address": "北京市西城区北三环中路25号",
                "storeHQCode": "A0GQ",
                "storePhone": "56084240",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "12",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011500",
                "countyName": "西城区",
                "name": "北京国美马甸鹏润店",
                "address": "北京市西城区北三环中路27号商房大厦",
                "storeHQCode": "A00V",
                "storePhone": "82074095",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010900",
        "countyName": "顺义区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "10130",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010900",
                "countyName": "顺义区",
                "name": "北京大中顺义店",
                "address": "北京市顺义区新顺南大街18号",
                "storeHQCode": "A0HO",
                "storePhone": "69433357",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "23",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010900",
                "countyName": "顺义区",
                "name": "北京国美顺义新顺店",
                "address": "北京市顺义区新顺南大街怡馨家园1号楼",
                "storeHQCode": "A01N",
                "storePhone": "69469075",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010300",
        "countyName": "丰台区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "2",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京国美洋桥店",
                "address": "北京市丰台区南三环中路73院国美电器",
                "storeHQCode": "A00C",
                "storePhone": "67222185",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "11",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京国美六里桥店",
                "address": "北京市丰台区西三环南路甲10号",
                "storeHQCode": "A003",
                "storePhone": "63333272",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "22",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京国美南三环店",
                "address": "北京市丰台区木樨园桥东9号双城公寓底层",
                "storeHQCode": "A006",
                "storePhone": "87290093",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "38",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中刘家窑店",
                "address": "北京市丰台区南三环东路6号嘉业大厦底商大中电器",
                "storeHQCode": "A0GX",
                "storePhone": "56084866",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10128",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中丰台桥南店",
                "address": "北京市丰台区西四环南路101号创新大厦一层",
                "storeHQCode": "A0I5",
                "storePhone": "56084999",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10134",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中洋桥店",
                "address": "北京市丰台区洋桥海户西里甲一号",
                "storeHQCode": "A0GS",
                "storePhone": "56084712",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10144",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中宝苑国际店",
                "address": "北京市丰台区南苑路88号宝苑国际购物中心二楼",
                "storeHQCode": "A0M1",
                "storePhone": "67000535",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10148",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中南四环集美店",
                "address": "北京市丰台区大红门南四环中路集美家居1号厅",
                "storeHQCode": "A0ID",
                "storePhone": "87885470",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10149",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010300",
                "countyName": "丰台区",
                "name": "北京大中云岗店",
                "address": "北京市丰台区南宫商业街3号恒源商厦地下一层",
                "storeHQCode": "A0H9",
                "storePhone": "56054938",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011800",
        "countyName": "延庆区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "24",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011800",
                "countyName": "延庆区",
                "name": "北京国美延庆店",
                "address": "北京市延庆区延庆镇妫水北街64号艺龙商城",
                "storeHQCode": "A00Q",
                "storePhone": "69101839",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10123",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011800",
                "countyName": "延庆区",
                "name": "北京大中延庆店",
                "address": "北京市延庆区延庆镇东外大街107号",
                "storeHQCode": "A0HJ",
                "storePhone": "69186557",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011200",
        "countyName": "怀柔区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "10126",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011200",
                "countyName": "怀柔区",
                "name": "北京大中怀柔店",
                "address": "北京市怀柔区青春路甲8号大中电器",
                "storeHQCode": "A0H4",
                "storePhone": "69633627",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11010400",
        "countyName": "石景山区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "29",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010400",
                "countyName": "石景山区",
                "name": "北京国美石景山万达店",
                "address": "北京市石景山区鲁古街道乙18号万达广场二层国美电器",
                "storeHQCode": "A014",
                "storePhone": "68685896",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "36",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010400",
                "countyName": "石景山区",
                "name": "北京大中玉泉路新店",
                "address": "北京石景山区鲁谷大街8号远洋山水底商",
                "storeHQCode": "A0HU",
                "storePhone": "56085288",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "33",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11010400",
                "countyName": "石景山区",
                "name": "北京大中石景山店",
                "address": "北京市石景山区石景山路22号长城大厦",
                "storeHQCode": "A0HE",
                "storePhone": "56084780",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011000",
        "countyName": "昌平区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "9",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011000",
                "countyName": "昌平区",
                "name": "北京国美天通苑店",
                "address": "北京市昌平区东小口镇龙德广场",
                "storeHQCode": "A00Z",
                "storePhone": "84810827",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10124",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011000",
                "countyName": "昌平区",
                "name": "北京大中昌平二店",
                "address": "北京市昌平区府学路24号",
                "storeHQCode": "A0HX",
                "storePhone": "80116563",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "26",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011000",
                "countyName": "昌平区",
                "name": "北京国美西关文化广场店",
                "address": "北京市昌平区城北街道西环路7号",
                "storeHQCode": "A01C",
                "storePhone": "89704514",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "39",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011000",
                "countyName": "昌平区",
                "name": "北京大中回龙观新店",
                "address": "北京市昌平区回龙观西大街118号龙冠置业大厦B座",
                "storeHQCode": "A0I4",
                "storePhone": "56085111",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    },
    {
        "countyCode": "11011300",
        "countyName": "平谷区",
        "gomeStoreShippings": [
            {
                "gomeStoreId": "41",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011300",
                "countyName": "平谷区",
                "name": "北京大中平谷二店",
                "address": "北京市平谷区新平北路53号",
                "storeHQCode": "A0HV",
                "storePhone": "56085277",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "13",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011300",
                "countyName": "平谷区",
                "name": "北京国美平谷店",
                "address": "北京市平谷区府前街29号国美电器",
                "storeHQCode": "A00I",
                "storePhone": "69986902",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            },
            {
                "gomeStoreId": "10131",
                "provinceCode": "11000000",
                "provinceName": "北京",
                "cityCode": "11010000",
                "cityName": "北京市",
                "countyCode": "11011300",
                "countyName": "平谷区",
                "name": "北京大中平谷府前街店",
                "address": "北京市平谷区新平东路13号",
                "storeHQCode": "A0IN",
                "storePhone": "56085221",
                "enabled": "1",
                "zoneCode": "010",
                "shopNo": "GOME",
                "support": true
            }
        ]
    }
]
};

